apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media
  namespace: media-home
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: standard
