apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: media-home
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
