image:
  repository: linuxserver/jackett
  tag: latest
  pullPolicy: IfNotPresent
env:
  TZ: "America/Santiago"
  ADVERTISE_IP: "192.168.100.99"
  ALLOWED_NETWORKS: "192.168.100.0/24"
service:
  main:
    primary: true
    type: ClusterIP
    ports:
      http:
        port: 9117
        protocol: TCP
        nodePort: 9117
ingress:
  main:
    enabled: true
    primary: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: "jackett.naitcloud.home"
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "jacket-server"
                port:
                  number: 9117
persistence:
  config:
    enabled: true
  torrentblackhole:
    enabled: false
