fullNameOverride: transmission
env:
  TZ: America/Santiago
  TRANSMISSION_WEB_HOME: /config/flood-for-transmission/
  TRANSMISSION_RPC_PASSWORD: a3onid230dx8nm12dps12ks1
  TRANSMISSION_DOWNLOAD_DIR: /downloads/complete
  TRANSMISSION_INCOMPLETE_DIR_ENABLED: true
  TRANSMISSION_INCOMPLETE_DIR: /downloads/incomplete
  TRANSMISSION_WATCH_DIR_ENABLED: false
image:
  repository: ghcr.io/k8s-at-home/transmission
  tag: v3.00
  pullPolicy: IfNotPresent
initContainers:
  custom-webui:
    name: custom-webui
    image: curlimages/curl:7.76.1
    command:
    - "/bin/sh"
    - "-c"
    - "curl -o- -sL https://github.com/johman10/flood-for-transmission/releases/download/latest/flood-for-transmission.tar.gz | tar -xzf - -C /config"
    volumeMounts:
    - name: config
      mountPath: /config
    securityContext:
       runAsUser: 568
       runAsGroup: 568
service:
  main:
    ports:
      http:
        port: 9091
  utptcp:
    enabled: true
    type: LoadBalancer
    ports:
      utptcp:
        enabled: true
        port: 32513
        protocol: TCP
        targetPort: 32513
    externalTrafficPolicy: Local
    externalIPs:
      - 192.168.0.206
      - 192.168.100.7
  utpudp:
    enabled: false
    type: NodePort
    ports:
      utpudp:
        enabled: true
        port: 32413
        protocol: UDP
        targetPort: 32513
ingress:
  main:
    enabled: true
    primary: true
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: transmission.naitcloud.home
        paths:
          - path: /
            pathType: Prefix
persistence:
  config:
    enabled: true
    accessMode: ReadWriteOnce
    size: 200Mi
    storageClass: standard
  downloads:
    enabled: true
    existingClaim: transmission-downloads
  watch:
    enabled: false
